server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5433/customer
    username: filipe
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true